/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_bluetooth_BluetoothStackBlueZNativeTests */

#ifndef _Included_com_intel_bluetooth_BluetoothStackBlueZNativeTests
#define _Included_com_intel_bluetooth_BluetoothStackBlueZNativeTests
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZNativeTests
 * Method:    testThrowException
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZNativeTests_testThrowException
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZNativeTests
 * Method:    testDebug
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZNativeTests_testDebug
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZNativeTests
 * Method:    testServiceRecordConvert
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZNativeTests_testServiceRecordConvert
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
