/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_bluetooth_BluetoothStackToshiba */

#ifndef _Included_com_intel_bluetooth_BluetoothStackToshiba
#define _Included_com_intel_bluetooth_BluetoothStackToshiba
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_bluetooth_BluetoothStackToshiba_ATTR_RETRIEVABLE_MAX
#define com_intel_bluetooth_BluetoothStackToshiba_ATTR_RETRIEVABLE_MAX 65535L
#undef com_intel_bluetooth_BluetoothStackToshiba_RECEIVE_MTU_MAX
#define com_intel_bluetooth_BluetoothStackToshiba_RECEIVE_MTU_MAX 1024L
/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    isNativeCodeLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_isNativeCodeLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    getLibraryVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_getLibraryVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    detectBluetoothStack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_detectBluetoothStack
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    enableNativeDebug
 * Signature: (Ljava/lang/Class;Z)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_enableNativeDebug
  (JNIEnv *, jobject, jclass, jboolean);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    initializeImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_initializeImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    destroyImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_destroyImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    getLocalDeviceBluetoothAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_getLocalDeviceBluetoothAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    runDeviceInquiryImpl
 * Signature: (Lcom/intel/bluetooth/DeviceInquiryThread;ILjavax/bluetooth/DiscoveryListener;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_runDeviceInquiryImpl
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    deviceInquiryCancelImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_deviceInquiryCancelImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    getRemoteDeviceFriendlyNameImpl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_getRemoteDeviceFriendlyNameImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    connectSDPImpl
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_connectSDPImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    disconnectSDPImpl
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_disconnectSDPImpl
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    searchServicesImpl
 * Signature: (Lcom/intel/bluetooth/SearchServicesThread;S[[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_searchServicesImpl
  (JNIEnv *, jobject, jobject, jshort, jobjectArray);

/*
 * Class:     com_intel_bluetooth_BluetoothStackToshiba
 * Method:    populateWorkerImpl
 * Signature: (SJ[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_bluetooth_BluetoothStackToshiba_populateWorkerImpl
  (JNIEnv *, jobject, jshort, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
