/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_bluetooth_BluetoothStackBlueSoleil */

#ifndef _Included_com_intel_bluetooth_BluetoothStackBlueSoleil
#define _Included_com_intel_bluetooth_BluetoothStackBlueSoleil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    isNativeCodeLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_isNativeCodeLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    getLibraryVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_getLibraryVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    detectBluetoothStack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_detectBluetoothStack
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    enableNativeDebug
 * Signature: (Ljava/lang/Class;Z)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_enableNativeDebug
  (JNIEnv *, jobject, jclass, jboolean);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    initializeImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_initializeImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_uninitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    getLocalDeviceBluetoothAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_getLocalDeviceBluetoothAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    getLocalDeviceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_getLocalDeviceName
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    getDeviceClassImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_getDeviceClassImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    isBlueSoleilStarted
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_isBlueSoleilStarted
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    isBluetoothReady
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_isBluetoothReady
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    getStackVersionInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_getStackVersionInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    getDeviceVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_getDeviceVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    getDeviceManufacturer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_getDeviceManufacturer
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    runDeviceInquiryImpl
 * Signature: (Lcom/intel/bluetooth/DeviceInquiryThread;ILjavax/bluetooth/DiscoveryListener;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_runDeviceInquiryImpl
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    cancelInquirympl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_cancelInquirympl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    runSearchServicesImpl
 * Signature: (Lcom/intel/bluetooth/SearchServicesThread;Ljavax/bluetooth/DiscoveryListener;[BJLjavax/bluetooth/RemoteDevice;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_runSearchServicesImpl
  (JNIEnv *, jobject, jobject, jobject, jbyteArray, jlong, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    connectionRfOpenImpl
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_connectionRfOpenImpl
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    connectionRfCloseClientConnection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_connectionRfCloseClientConnection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    rfServerOpenImpl
 * Signature: ([BLjava/lang/String;ZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_rfServerOpenImpl
  (JNIEnv *, jobject, jbyteArray, jstring, jboolean, jboolean);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    rfServerSCN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_rfServerSCN
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    rfServerAcceptAndOpenRfServerConnection
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_rfServerAcceptAndOpenRfServerConnection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    rfServerClose
 * Signature: (JLcom/intel/bluetooth/ServiceRecordImpl;)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_rfServerClose
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    getConnectionRfRemoteAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_getConnectionRfRemoteAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    connectionRfRead
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_connectionRfRead__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    connectionRfRead
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_connectionRfRead__J_3BII
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    connectionRfReadAvailable
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_connectionRfReadAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    connectionRfWrite
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_connectionRfWrite__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    connectionRfWrite
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_connectionRfWrite__J_3BII
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueSoleil
 * Method:    connectionRfFlush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueSoleil_connectionRfFlush
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
