/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_bluetooth_BluetoothStackOSX */

#ifndef _Included_com_intel_bluetooth_BluetoothStackOSX
#define _Included_com_intel_bluetooth_BluetoothStackOSX
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_bluetooth_BluetoothStackOSX_debug
#define com_intel_bluetooth_BluetoothStackOSX_debug 0L
#undef com_intel_bluetooth_BluetoothStackOSX_ATTR_RETRIEVABLE_MAX
#define com_intel_bluetooth_BluetoothStackOSX_ATTR_RETRIEVABLE_MAX 256L
#undef com_intel_bluetooth_BluetoothStackOSX_BLUETOOTH_SOFTWARE_VERSION_2_0_0
#define com_intel_bluetooth_BluetoothStackOSX_BLUETOOTH_SOFTWARE_VERSION_2_0_0 20000L
/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    isNativeCodeLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_isNativeCodeLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getLibraryVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getLibraryVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    detectBluetoothStack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_detectBluetoothStack
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    initializeImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_initializeImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    enableNativeDebug
 * Signature: (Ljava/lang/Class;Z)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_enableNativeDebug
  (JNIEnv *, jobject, jclass, jboolean);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getLocalDeviceBluetoothAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getLocalDeviceBluetoothAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getLocalDeviceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getLocalDeviceName
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getDeviceClassImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getDeviceClassImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    setLocalDeviceServiceClassesImpl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_setLocalDeviceServiceClassesImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    isLocalDevicePowerOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_isLocalDevicePowerOn
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    isLocalDeviceFeatureSwitchRoles
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_isLocalDeviceFeatureSwitchRoles
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    isLocalDeviceFeatureParkMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_isLocalDeviceFeatureParkMode
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getLocalDeviceL2CAPMTUMaximum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getLocalDeviceL2CAPMTUMaximum
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getLocalDeviceSupportedSoftwareVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getLocalDeviceSupportedSoftwareVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getLocalDeviceSoftwareVersionInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getLocalDeviceSoftwareVersionInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getLocalDeviceManufacturer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getLocalDeviceManufacturer
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getLocalDeviceVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getLocalDeviceVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getLocalDeviceDiscoverableImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getLocalDeviceDiscoverableImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getRemoteDeviceFriendlyName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getRemoteDeviceFriendlyName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    runDeviceInquiryImpl
 * Signature: (Lcom/intel/bluetooth/DeviceInquiryRunnable;Lcom/intel/bluetooth/DeviceInquiryThread;IILjavax/bluetooth/DiscoveryListener;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_runDeviceInquiryImpl
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    deviceInquiryCancelImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_deviceInquiryCancelImpl
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    runSearchServicesImpl
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_runSearchServicesImpl
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    cancelServiceSearchImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_cancelServiceSearchImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getServiceAttributeImpl
 * Signature: (JJI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getServiceAttributeImpl
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    connectionRfOpenClientConnectionImpl
 * Signature: (JIZZI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_connectionRfOpenClientConnectionImpl
  (JNIEnv *, jobject, jlong, jint, jboolean, jboolean, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    connectionRfCloseClientConnection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_connectionRfCloseClientConnection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    rfGetSecurityOpt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_rfGetSecurityOpt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    rfServerCreateImpl
 * Signature: ([BZLjava/lang/String;ZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_rfServerCreateImpl
  (JNIEnv *, jobject, jbyteArray, jboolean, jstring, jboolean, jboolean);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    rfServerGetChannelID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_rfServerGetChannelID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    rfServerCloseImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_rfServerCloseImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    rfServerAcceptAndOpenRfServerConnection
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_rfServerAcceptAndOpenRfServerConnection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    sdpServiceUpdateServiceRecordPublish
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_sdpServiceUpdateServiceRecordPublish
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    sdpServiceAddAttribute
 * Signature: (JCIIJ[B)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_sdpServiceAddAttribute
  (JNIEnv *, jobject, jlong, jchar, jint, jint, jlong, jbyteArray);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    sdpServiceSequenceAttributeStart
 * Signature: (JCII)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_sdpServiceSequenceAttributeStart
  (JNIEnv *, jobject, jlong, jchar, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    sdpServiceSequenceAttributeEnd
 * Signature: (JCI)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_sdpServiceSequenceAttributeEnd
  (JNIEnv *, jobject, jlong, jchar, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    connectionRfRead
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_connectionRfRead__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    connectionRfRead
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_connectionRfRead__J_3BII
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    connectionRfReadAvailable
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_connectionRfReadAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    connectionRfWrite
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_connectionRfWrite
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    getConnectionRfRemoteAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_getConnectionRfRemoteAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2OpenClientConnectionImpl
 * Signature: (JIZZIII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2OpenClientConnectionImpl
  (JNIEnv *, jobject, jlong, jint, jboolean, jboolean, jint, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2CloseClientConnection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2CloseClientConnection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2ServerOpenImpl
 * Signature: ([BZZLjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2ServerOpenImpl
  (JNIEnv *, jobject, jbyteArray, jboolean, jboolean, jstring, jint, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2ServerPSM
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2ServerPSM
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2ServerAcceptAndOpenServerConnection
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2ServerAcceptAndOpenServerConnection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2ServerCloseImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2ServerCloseImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2GetSecurityOpt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2GetSecurityOpt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2Ready
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2Ready
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2Receive
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2Receive
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2Send
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2Send
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2GetReceiveMTU
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2GetReceiveMTU
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2GetTransmitMTU
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2GetTransmitMTU
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackOSX
 * Method:    l2RemoteAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackOSX_l2RemoteAddress
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
