/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_bluetooth_BluetoothStackMicrosoft */

#ifndef _Included_com_intel_bluetooth_BluetoothStackMicrosoft
#define _Included_com_intel_bluetooth_BluetoothStackMicrosoft
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_bluetooth_BluetoothStackMicrosoft_BTH_MODE_POWER_OFF
#define com_intel_bluetooth_BluetoothStackMicrosoft_BTH_MODE_POWER_OFF 1L
#undef com_intel_bluetooth_BluetoothStackMicrosoft_BTH_MODE_CONNECTABLE
#define com_intel_bluetooth_BluetoothStackMicrosoft_BTH_MODE_CONNECTABLE 2L
#undef com_intel_bluetooth_BluetoothStackMicrosoft_BTH_MODE_DISCOVERABLE
#define com_intel_bluetooth_BluetoothStackMicrosoft_BTH_MODE_DISCOVERABLE 3L
#undef com_intel_bluetooth_BluetoothStackMicrosoft_ATTR_RETRIEVABLE_MAX
#define com_intel_bluetooth_BluetoothStackMicrosoft_ATTR_RETRIEVABLE_MAX 256L
/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    isNativeCodeLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_isNativeCodeLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getLibraryVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getLibraryVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    detectBluetoothStack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_detectBluetoothStack
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    enableNativeDebug
 * Signature: (Ljava/lang/Class;Z)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_enableNativeDebug
  (JNIEnv *, jobject, jclass, jboolean);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    initializationStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_initializationStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_uninitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    isWindowsCE
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_isWindowsCE
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getDeviceClass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getDeviceClass
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    setDiscoverable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_setDiscoverable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getBluetoothRadioMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getBluetoothRadioMode
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getradioname
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getradioname
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getDeviceVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getDeviceVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getDeviceManufacturer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getDeviceManufacturer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    retrieveDevicesImpl
 * Signature: (ILcom/intel/bluetooth/RetrieveDevicesCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_retrieveDevicesImpl
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    isRemoteDeviceTrustedImpl
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_isRemoteDeviceTrustedImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    isRemoteDeviceAuthenticatedImpl
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_isRemoteDeviceAuthenticatedImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    authenticateRemoteDeviceImpl
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_authenticateRemoteDeviceImpl
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    removeAuthenticationWithRemoteDeviceImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_removeAuthenticationWithRemoteDeviceImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    runDeviceInquiryImpl
 * Signature: (Lcom/intel/bluetooth/DeviceInquiryRunnable;Lcom/intel/bluetooth/DeviceInquiryThread;IILjavax/bluetooth/DiscoveryListener;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_runDeviceInquiryImpl
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    cancelInquiry
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_cancelInquiry
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    runSearchServicesImpl
 * Signature: ([Ljavax/bluetooth/UUID;J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_runSearchServicesImpl
  (JNIEnv *, jobject, jobjectArray, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getServiceAttributes
 * Signature: ([IJI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getServiceAttributes
  (JNIEnv *, jobject, jintArray, jlong, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    socket
 * Signature: (ZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_socket
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getsockaddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getsockaddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    storesockopt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_storesockopt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getsockchannel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getsockchannel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    connect
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_connect
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    bind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_bind
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    listen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_listen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    accept
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_accept
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    recvAvailable
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_recvAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    recv
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_recv__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    recv
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_recv__J_3BII
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    send
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_send__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    send
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_send__J_3BII
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getpeername
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getpeername
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    getpeeraddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_getpeeraddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    registerService
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_registerService
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackMicrosoft
 * Method:    unregisterService
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackMicrosoft_unregisterService
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
