#!/bin/bash
#This is the main installation file for the pjbluez library
source envvariables
if [ ! -e $BIN_DIR ]; then
	mkdir $BIN_DIR
fi
autoheader
autoconf
sh configure --with-jdk=$JDK_HOME --with-javaplatform=$JDK_PLATFORM --with-bindir=$BIN_DIR
make all
